[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from   = "/api/*"
  to     = "https://backend-bookhive.onrender.com/api/:splat"
  status = 200
  force  = true